-- BOARD 테이블 생성
DROP TABLE BOARD;

CREATE TABLE BOARD(
    BNO NUMBER PRIMARY KEY, -- 게시글 번호
    TITLE VARCHAR2(50) NOT NULL, -- 게시글 제목
    CONTENT VARCHAR2(500) NOT NULL, -- 게시글 내용
    CREATE_DATE DATE DEFAULT SYSDATE, -- 작성일
    WRITER NUMBER, -- 작성자(회원번호)
    DELETE_YN CHAR(2) DEFAULT 'N', -- 게시글 삭제 여부(N : 삭제가 안된 상태)
    FOREIGN KEY (WRITER) REFERENCES MEMBER(USERNO),
    CHECK(DELETE_YN IN('Y','N'))
);

-- BOARD 테이블의 PK로 사용될 시퀀스
DROP SEQUENCE SEQ_BOARD;

CREATE SEQUENCE SEQ_BOARD;

-- 테스트 데이터 삽입
INSERT INTO BOARD
VALUES(SEQ_BOARD.NEXTVAL, '게시판 서비스를 시작합니다^^', '많은 이용 바랍니다~!', '21/01/27', 1, DEFAULT);

INSERT INTO BOARD
VALUES(SEQ_BOARD.NEXTVAL, 'JDBC 어려워요', '살려주세요', '21/09/05', 2, DEFAULT);

INSERT INTO BOARD
VALUES(SEQ_BOARD.NEXTVAL, '게시글2', '게시글2 내용은 도대체 뭘까요?', '21/09/05', 2, DEFAULT);

COMMIT;

SELECT * FROM BOARD;

-- 게시글 전체 조회
SELECT BNO, TITLE, CREATE_DATE,WRITER, USERID
FROM BOARD, MEMBER
WHERE WRITER = USERNO 
  AND DELETE_YN = 'N' -- 삭제가 되지 않은 게시글만 보임.
ORDER BY CREATE_DATE DESC;  -- 최신글 순으로 

-- 게시글 삭제 
UPDATE BOARD
   SET DELETE_YN = 'Y'
 WHERE BNO = ?;
